server:
    isProd: false
    port: 8585
    pg:
        user: "db00_user"
        password: "your@password"
        host: "155.212.130.21"
        port: 5432
        database: "db00"
        sllmode: "disable"